### ISSUE TITLE
Cocoapods please!

### ISSUE THREAD

**Issue by lfarah** [tarunon/AnyObjectConvertible#2]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by tarunon** [comment]
Hi @lfarah , Thanks for your request!

I'm sorry I was late... 
But now, I completed upload to Cocoapods 👍 

``` shell
  - Log messages:
    - June 6th, 21:37: Push for `AnyObjectConvertible 0.0.3' initiated.
    - June 6th, 21:37: Push for `AnyObjectConvertible 0.0.3' has been pushed
    (2.244339624 s).
```

Please waiting to be reflected. Thanks.

**Comment by tarunon** [comment]
Now completable cocoapods 😄 
https://cocoapods.org/pods/AnyObjectConvertible

Thanks all.

**Comment by lfarah** [comment]
Awesome. Congrats! 😃
